name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: |
        echo $CWD
        cargo +nightly build --verbose --manifest-path Cargo.toml
    - name: Run tests
      run: |
        echo $CWD
        cargo +nightly test --verbose --manifest-path Cargo.toml
